name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/student-backend
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG student-attendance-backend
          docker push $IMAGE:$TAG

      - name: Update Deployment YAML
        run: |
          sed -i "s|image: .*/student-backend:.*|image:docker.io/${{ secrets.DOCKERHUB_USERNAME }}/student-backend:${{ github.sha }}|g" k8s/student-backend-deploy.yaml

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update student-backend image to ${{ github.sha }}"
          add: "k8s/student-backend-deploy.yaml"
